spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to QA prop."
  contactDetails:
    name: "jordi"
    email: "odjod@hotma.com"
  onCallSupport:
    - "Jordi DS"